/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.mfizz.util;
public final class Version {
    private static final String TIMESTAMP="20120906-2035";
    private static final String VERSION="1.0.0";
    private static final String NAME="mfz-util";
    private static final String VENDOR="com.mfizz";
    private static final String LONG_VERSION="1.0.0 (Build @ 20120906-2035)";
    /** Returns the library vendor such as "com.mfizz" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20120906-2035" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "mfz-util" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "1.0.0" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "1.0.0 (Build @ 20120906-2035)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
